baseURL = "https://chaojia.github.io/"
title = "Chao Jia"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "description of Chao"
title404 = "Nothing here"

[params.assets]
favicon = "images/chao.ico"
customCSS = ["css/tooltip.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Chao Jia"
startYear = "2022"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "Mon, 02 Jan 2006 15:04"
listDateFormat = "02 Jan 2006"
archiveDateFormat = "02 Jan"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = false
showLastmod = false
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = true

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud", "social_menu"]

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "chao.cj.jia@gmail.com"
github = "ChaoJia"
gitlab = "chao-jia"

[params.comments]
enable = true

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = true 
issueTerm = "pathname" # pathname / url / title / og:title / <string>
label = ""
theme = "github-light"

[params.comments.utterances.github]
username = "ChaoJia"
repository = "chaojia.github.io"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
